In [1]:
import requests
from scrapy import Selector
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

In [2]:
# Set up Chrome options for Selenium
chrome_options = webdriver.ChromeOptions()
chrome_options = Options()
chrome_options.add_argument("--headless")  # Run browser in headless mode
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--no-sandbox")

In [3]:
service = Service(ChromeDriverManager().install())

In [4]:
driver = webdriver.Chrome(service=service, options=chrome_options)

In [5]:
url = 'https://www.shopsy.in/smart-watches-online'
driver.get(url)

In [6]:
page_source = driver.page_source

In [7]:
sel = Selector(text=page_source)

In [8]:
name=sel.css("div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div.css-146c3p1.r-dnmrzs.r-1udh08x.r-1udbk01.r-3s2u2q.r-1iln25a > span::text").getall()
name

["Noise Colorfit Icon 2 1.8'' Display with Bluetooth Calling, AI Voice Assistant Smartwatch",
 'Fire-Boltt Rise Bluetooth Calling 47mm (1.85), Metal Bod & Rotating Crown, 123 Sports Smartwatch',
 'Techy Alpha T500 Ultra Bluetooth calling,sports 5G speed Smartwatch Smartwatch',
 'Avonix C9 Ultra Dark Golden BT Microphone Calling with 25+ New Features NO Color Fade_ Smartwatch',
 "Noise Colorfit Icon 2 1.8'' Display with Bluetooth Calling, AI Voice Assistant Smartwatch",
 'Vinayak T800 smart watch & S8 4G network Sim Card Android System T10 Ultra T21 Smartwatch',
 'Luyten tech Latest Modal of Ultra Watch With 7 Straps & Best Quality Smartwatch',
 'Noise Icon Buzz 1.69" Display with Bluetooth Calling, Built-In Games, Voice Assistant Smartwatch',
 'DOPEWOPE T800 Ultra Honeycomb smart watch & SIM card 4G network Android System T2 Smartwatch',
 "Noise Mettle 1.4'' display, Stainless Steel finish with Metal Strap, Bluetooth Calling Smartwatch",
 "Noise Colorfit Icon 2 1.8'' Display with Bluetooth Calling, AI Voice Assistant Smartwatch",
 'BOOMLY T800 ULTRA SMARTWATCH 1.9 HD DISPLAY ING WATCH Smartwatch',
 "Noise Caliber 2 Buzz 1.85'' Display with Bluetooth Calling, Long Battery & IP68 Rating Smartwatch",
 'FEEL FLON T800 Ultra Pro Edition smart watch with WiFi GPS SIM card 5G ultra watch Smartwatch',
 "Boult CrownR Pro 1.43''HD AMOLED, BT Calling, Zinc Alloy Frame, IP67, SpO2 Tracking Smartwatch",
 'Boult Drift BT Calling HD Display, 140+ Watchfaces, Complete Health Monitoring Smartwatch',
 "Noise Colorfit Icon 2 1.8'' Display with Bluetooth Calling, AI Voice Assistant Smartwatch",
 'ROCK TOUCH T800 Ultra Pro Edition smart watch with WiFi GPS SIM card 5G ultra watch Smartwatch',
 'Fire-Boltt Hurricane 33.02mm (1.3) Curved Glass Display with BT Calling, 100+ Sports Modes Smartwatch',
 'Melbon T800 Ultra Smart Watch: 1.99" Touch Display, BT Calling, with Multiple Features Smartwatch',
 'Paradise T10 Ultra orange Smart Watch Display, Bluetooth Calling HD Smart 5G Network Smartwatch',
 'ROCK TOUCH T800 Ultra Smartwatch BT Calling 1.99" HD Display for Men & Women Smartwatch',
 'INNOMAX S20 Force 2.01" Display Smart Watch with Bluetooth Calling, for Men and Women Smartwatch',
 'Fire-Boltt Hurricane 33.02mm (1.3) Curved Glass Display with BT Calling, 100+ Sports Modes Smartwatch',
 'Noise Icon Buzz 1.69" Display with Bluetooth Calling, Built-In Games, Voice Assistant Smartwatch',
 'FORTUNATE T800 ultra Full screen Smart Watch Series 8 For Men & Women Smartwatch',
 "Noise Loop 1.85'' Display with Advanced Bluetooth Calling, 550 Nits Brightness Smartwatch",
 "Noise Caliber 2 Buzz 1.85'' Display with Bluetooth Calling, Long Battery & IP68 Rating Smartwatch",
 "boAt Wave Fury with 1.83'' HD Display, Bluetooth Calling & Functional Crown Smartwatch",
 'Trenzu T800 ULTRA Smart Watch No sim card Opetion Smartwatch Smartwatch',
 'zdea T800 ULTRA Smart Watch No sim card Opetion Smartwatch NO sim card Smartwatch',
 'Fire-Boltt Ninja Talk 35.3mm (1.39) Round Bluetooth Calling Metal Body,120 Sports Modes Smartwatch',
 "Noise Icon 2 Elite Edition 1.8'' Display with Metallic Body and Bluetooth Calling Smartwatch",
 'TECHMAZE T800 Ultra ulta1 Smartwatch',
 'Moktu Android Smart Watch2 Men 4G Network BT Call GPS T800 Ultra Smartwatch Smartwatch',
 'Vinayak UltraT-800 Smartwatch Series 8 Bluetooth Call 4G Network Ultra 8 Smartwatch',
 "Fastrack Revoltt FS1-1.83''|BT Calling|Fast Charge|110+ Sports Mode|200+ WatchFaces|IP68 Smartwatch",
 "Noise Icon 2 1.8'' Display with Bluetooth Calling, Women's Edition, AI Voice Assistant Smartwatch",
 "boAt Wave Fury with 1.83'' HD Display, Bluetooth Calling & Functional Crown Smartwatch",
 'TECHMAZE T800 ultra smart watch with wireless charging Smartwatch']

In [9]:
offer = sel.css("div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div::text").getall()
offer

['80% off',
 '88% off',
 '74% off',
 '60% off',
 '81% off',
 '4.3',
 '84% off',
 '80% off',
 '82% off',
 '76% off',
 '81% off',
 '88% off',
 '81% off',
 '70% off',
 '71% off',
 '85% off',
 '80% off',
 '67% off',
 '83% off',
 '76% off',
 '70% off',
 '67% off',
 '86% off',
 '83% off',
 '80% off',
 '82% off',
 '85% off',
 '81% off',
 '81% off',
 '85% off',
 '85% off',
 '88% off',
 '78% off',
 '80% off',
 '77% off',
 '3.7',
 '69% off',
 '81% off',
 '81% off',
 '81% off']

In [12]:
price = sel.css("div.css-175oi2r.r-1rngwi6 > div.css-146c3p1.r-1h7g6bg.r-1vgyyaa.r-1rsjblm.r-142tt33.r-11wrixw::text").getall()
price

['5,999',
 '1,699',
 '11,999',
 '1,999',
 '5,999',
 '4,999',
 '5,399',
 '4,299',
 '4,999',
 '2,999',
 '5,999',
 '4,999',
 '5,999',
 '1,999',
 '6,999',
 '7,999',
 '5,999',
 '1,799',
 '8,999',
 '2,999',
 '1,999',
 '1,699',
 '4,799',
 '8,999',
 '4,999',
 '2,999',
 '6,999',
 '4,999',
 '2,999',
 '5,999',
 '6,999',
 '4,999',
 '4,999',
 '11,999',
 '6,999',
 '2,999',
 '3,049',
 '4,999',
 '3,995',
 '5,999']

In [13]:
sel.css("div > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div:nth-child(1) > div.css-175oi2r.r-1rngwi6 > div.css-146c3p1.r-cqee49.r-1vgyyaa.r-1rsjblm.r-13hce6t::text").getall()

['₹1,309',
 '₹670',
 '₹1,599',
 '₹516',
 '₹1,399',
 '₹609',
 '₹853',
 '₹581',
 '₹1,099',
 '₹538',
 '₹1,399',
 '₹560',
 '₹1,399',
 '₹595',
 '₹2,399',
 '₹1,399',
 '₹1,199',
 '₹587',
 '₹1,599',
 '₹699',
 '₹589',
 '₹556',
 '₹638',
 '₹1,599',
 '₹1,099',
 '₹518',
 '₹1,099',
 '₹1,299',
 '₹536',
 '₹1,399',
 '₹1,399',
 '₹717',
 '₹710',
 '₹1,599',
 '₹1,599',
 '₹670',
 '₹591',
 '₹609',
 '₹1,299',
 '₹1,399']

In [14]:
sel.css("div > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div.css-175oi2r.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md.r-f1odvy > div > div:nth-child(2) > div > div::text").getall()

['(6,93,112)',
 '(17)',
 '(1,38,630)',
 '(14)',
 '(6,93,112)',
 '(7)',
 '(30)',
 '(10)',
 '(6,25,093)',
 '(8)',
 '(6,93,112)',
 '(8)',
 '(38,699)',
 '(6)',
 '(31,617)',
 '(3,12,226)',
 '(6,93,112)',
 '(5)',
 '(2,81,657)',
 '(84)',
 '(10)',
 '(7)',
 '(143)',
 '(2,81,657)',
 '(6,25,093)',
 '(23)',
 '(62,838)',
 '(6,25,093)',
 '(73)',
 '(38,699)',
 '(70,889)',
 '(3)',
 '(5)',
 '(3,67,145)',
 '(6,93,112)',
 '(3)',
 '(6)',
 '(8)',
 '(3,07,338)',
 '(6,93,112)']

In [15]:
sel.css("div > div > div:nth-child(1) > div > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div.css-175oi2r.r-18u37iz.r-1d09ksm.r-1w6e6rj.r-kc8jnq > div:nth-child(1)::text").getall()

['Upto ',
 'Upto ',
 'Only few left',
 'Only 1 left',
 'Only 4 left',
 'Only few left',
 'Upto ',
 'Only few left',
 'Only few left',
 'Only few left']

In [33]:
sel.css("div.css-175oi2r.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md.r-f1odvy > div > div.css-175oi2r.r-1awozwy.r-cdmcib.r-jwli3a.r-6koalj.r-18u37iz.r-1enofrn.r-1ss6j8a > div").getall()

['<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">3.4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.7</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.7</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.7</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.7</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.1</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.2</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.1</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.3</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.3</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.3</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.2</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.2</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.7</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.5</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.1</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.8</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.2</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">5</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.2</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.1</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.1</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.2</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">5</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.1</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">5</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.5</div>',
 '<div dir="auto" class="css-146c3p1 r-jwli3a r-1et8rh5 r-1enofrn">4.7</div>']

In [ ]:
sel.css("")

In [ ]:


# List of URLs
links =['https://www.shopsy.in/smart-watches-online',
        'https://www.shopsy.in/smart-watches-online/pr?page=2',
        'https://www.shopsy.in/smart-watches-online/pr?page=3',
        'https://www.shopsy.in/smart-watches-online/pr?page=4',
        'https://www.shopsy.in/smart-watches-online/pr?page=5',
        'https://www.shopsy.in/smart-watches-online/pr?page=6',
        'https://www.shopsy.in/smart-watches-online/pr?page=7',
        'https://www.shopsy.in/smart-watches-online/pr?page=8',
        'https://www.shopsy.in/smart-watches-online/pr?page=9',
        'https://www.shopsy.in/smart-watches-online/pr?page=10',
        'https://www.shopsy.in/smart-watches-online/pr?page=11',
        'https://www.shopsy.in/smart-watches-online/pr?page=12',
        'https://www.shopsy.in/smart-watches-online/pr?page=13',
        'https://www.shopsy.in/smart-watches-online/pr?page=14',
        'https://www.shopsy.in/smart-watches-online/pr?page=15',
        'https://www.shopsy.in/smart-watches-online/pr?page=16',
        #'https://www.shopsy.in/smart-watches-online/pr?page=17',
        #'https://www.shopsy.in/smart-watches-online/pr?page=18',
        #'https://www.shopsy.in/smart-watches-online/pr?page=19',
        #'https://www.shopsy.in/smart-watches-online/pr?page=20',
        #'https://www.shopsy.in/smart-watches-online/pr?page=21',
          ]
    

# List to store scraped data
data = []

# Iterate over each URL
for link in links:
    try:
        # Make a request to each URL
        response = requests.get(link, headers={"User-Agent": "Mozilla/5.0"})
        response.raise_for_status()  # Check if the request was successful
        
        # Parse the HTML response
        sel = Selector(text=response.text)
        
        # Extract data
        product_names = sel.css("div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div.css-146c3p1.r-dnmrzs.r-1udh08x.r-1udbk01.r-3s2u2q.r-1iln25a > span::text").getall()
        offer = sel.css("div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div::text").getall()
        product_price = sel.css("div.css-175oi2r.r-1rngwi6 > div.css-146c3p1.r-1h7g6bg.r-1vgyyaa.r-1rsjblm.r-142tt33.r-11wrixw::text").getall()
        discount_price = sel.css("div > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div:nth-child(1) > div.css-175oi2r.r-1rngwi6 > div.css-146c3p1.r-cqee49.r-1vgyyaa.r-1rsjblm.r-13hce6t::text").getall()
        reviwe = sel.css("div.css-175oi2r.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md.r-f1odvy > div > div:nth-child(2) > div > div::text").getall()
        retings = sel.css("div.css-175oi2r.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md.r-f1odvy > div > div.css-175oi2r.r-1awozwy.r-cdmcib.r-jwli3a.r-6koalj.r-18u37iz.r-1enofrn.r-1ss6j8a > div::text").getall()
        deliverry = sel.css("div:nth-child(1) > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div.css-175oi2r.r-1awozwy.r-18u37iz > div > div::text").getall()
        #ratings = sel.css("._5OesEi::text").getall()
        #warranty = sel.css("ul > li:nth-child(6)::text").getall()

        # Store data in list
        for i in range(len(product_names)):
            data.append({
                "Product Name": product_names[i] if i < len(product_names) else None,
                "Offer": offer[i] if i < len(offer) else None,
                "Product_price": product_price[i] if i < len(product_price) else None,
                "Discount_price": discount_price[i] if i < len(discount_price) else None,
                "Reviwe": reviwe [i] if i < len(reviwe) else None,
                "Reting": retings[i] if i < len(retings) else None,
                "Delivery":deliverry[i] if i < len(deliverry) else None,
                #"Ratings": ratings[i] if i < len(ratings) else None,
                #"Warranty": warranty[i] if i < len(warranty) else None
            })
    except requests.exceptions.RequestException as e:
        print(f"Error fetching {link}: {e}")

# Convert data to DataFrame and save to CSV
if data:
    df = pd.DataFrame(data)
    df.to_csv("1.csv", index=False)
    

df

,Product Name,Offer,Product_price,Discount_price,Reviwe,Reting,Delivery
0,Yash Enterprises New T800 Ultra Watch compatia...,68% off,"1,504",₹473,(32),4,Free delivery
1,Noise Colorfit Icon 2 1.8'' Display with Bluet...,80% off,"5,999","₹1,199","(6,94,114)",4.1,Free delivery
2,"Fire-Boltt Rise Bluetooth Calling 47mm (1.85),...",88% off,"11,999","₹1,399","(1,38,914)",4,Free delivery
3,Avonix C9 Ultra Dark Golden BT Microphone Call...,60% off,"1,999",₹791,(13),4.3,Free delivery
4,"boAt Storm Call w/ 4.29 cm(1.69""), BT Calling ...",84% off,"7,990","₹1,249","(3,50,408)",4.1,Free delivery
...,...,...,...,...,...,...,...
635,Fastrack FR1|1.39 inch Super UltraVU Display(3...,66% off,"5,995","₹1,999","(13,352)",4.2,Free delivery
636,"Pebble Hive 1.39""HD Octa Display,BT Calling, H...",73% off,"6,499","₹1,699","(2,511)",4.1,Free delivery
637,"Noise Diva 2 Women's Collection, 36mm AMOLED D...",35% off,"6,999","₹4,499",(215),4.2,Free delivery
638,HGT Gen 9 Model Smartwatch: The Next Generatio...,82% off,"6,999","₹1,217",(78),4.1,Free delivery
639,Noise Evolve 4 1.46 AMOLED Always On Display w...,68% off,"7,999","₹2,499","(3,758)",4.3,Free delivery

In [25]:
null_count = df['Product_price'].isnull().sum()

print("Number of null values in 'product_price':", null_count)

Number of null values in 'product_price': 47

In [26]:
null_count = df['Discount_price'].isnull().sum()

print("Number of null values in 'kk':", null_count)

Number of null values in 'kk': 47

In [28]:
null_counts = df[['Reviwe', 'Reting', 'Delivery']].isnull().sum()

print("Number of null values in each variable:")
print(null_counts)

Number of null values in each variable:
Reviwe      1
Reting      1
Delivery    0
dtype: int64

In [9]:
url1 = 'https://www.shopsy.in/watches-online'
driver.get(url1)

In [15]:
# List of URLs
links1 =['https://www.shopsy.in/watches-online',
        'https://www.shopsy.in/watches-online/pr?page=2',
        'https://www.shopsy.in/watches-online/pr?page=3',
        'https://www.shopsy.in/watches-online/pr?page=4',
        'https://www.shopsy.in/watches-online/pr?page=5',
        'https://www.shopsy.in/watches-online/pr?page=6',
        'https://www.shopsy.in/watches-online/pr?page=7',
        'https://www.shopsy.in/watches-online/pr?page=8',
        'https://www.shopsy.in/watches-online/pr?page=9',
        'https://www.shopsy.in/watches-online/pr?page=10',
        'https://www.shopsy.in/watches-online/pr?page=11',
        'https://www.shopsy.in/watches-online/pr?page=12',
        'https://www.shopsy.in/watches-online/pr?page=13',
        'https://www.shopsy.in/watches-online/pr?page=14',
        'https://www.shopsy.in/watches-online/pr?page=15',
        'https://www.shopsy.in/watches-online/pr?page=16',
        'https://www.shopsy.in/watches-online/pr?page=17',
        'https://www.shopsy.in/watches-online/pr?page=18',
        'https://www.shopsy.in/watches-online/pr?page=19',
        'https://www.shopsy.in/watches-online/pr?page=20',
        'https://www.shopsy.in/watches-online/pr?page=21',
        'https://www.shopsy.in/watches-online/pr?page=22',
        'https://www.shopsy.in/watches-online/pr?page=23',
        'https://www.shopsy.in/watches-online/pr?page=24',
        'https://www.shopsy.in/watches-online/pr?page=25',
        ]
    

# List to store scraped data
data1 = []

# Iterate over each URL
for link in links1:
    try:
        # Make a request to each URL
        response = requests.get(link, headers={"User-Agent": "Mozilla/5.0"})
        response.raise_for_status()  # Check if the request was successful
        
        # Parse the HTML response
        sel = Selector(text=response.text)
        
        # Extract data
        iteam_name = sel.css("div > div:nth-child(1) > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div.css-146c3p1.r-dnmrzs.r-1udh08x.r-1udbk01.r-3s2u2q.r-1iln25a > span::text").getall()
        offer_1 = sel.css("div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div:nth-child(1) > div:nth-child(1) > div::text").getall()
        iteam_price = sel.css("div > div:nth-child(1) > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div:nth-child(1) > div.css-175oi2r.r-1rngwi6 > div.css-146c3p1.r-1h7g6bg.r-1vgyyaa.r-1rsjblm.r-142tt33.r-11wrixw::text").getall()
        offer_price = sel.css("div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div:nth-child(1) > div.css-175oi2r.r-1rngwi6 > div.css-146c3p1.r-cqee49.r-1vgyyaa.r-1rsjblm.r-13hce6t::text").getall()
        reviwe1 = sel.css("div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div.css-175oi2r.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md.r-f1odvy > div > div:nth-child(2) > div > div::text").getall()
        retings1 = sel.css("div:nth-child(1) > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div.css-175oi2r.r-1awozwy.r-13awgt0.r-18u37iz.r-1h0z5md.r-f1odvy > div > div.css-175oi2r.r-1awozwy.r-cdmcib.r-jwli3a.r-6koalj.r-18u37iz.r-1enofrn.r-1ss6j8a > div::text").getall()
        delivery= sel.css("div:nth-child(1) > div > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md > div > div.css-175oi2r.r-1habvwh.r-eqz5dr.r-1h0z5md.r-cnw61z.r-1ss6j8a.r-1hvjb8t > div:nth-child(2) > div.css-175oi2r.r-1awozwy.r-18u37iz > div > div::text").getall()
        #warranty = sel.css("ul > li:nth-child(6)::text").getall()

        # Store data in list
        for i in range(len(iteam_name)):
            data1.append({
                "Product Name": iteam_name[i] if i < len(iteam_name) else None,
                "Offer": offer_1[i] if i < len(offer_1) else None,
                "Product_price": iteam_price[i] if i < len(iteam_price) else None,
                "Discount_price": offer_price[i] if i < len(offer_price) else None,
                "Reviwe": reviwe1 [i] if i < len(reviwe1) else None,
                "Reting": retings1[i] if i < len(retings1) else None,
                "Delivery":delivery[i] if i < len(delivery) else None,
                #"Ratings": ratings[i] if i < len(ratings) else None,
                #"Warranty": warranty[i] if i < len(warranty) else None
            })
    except requests.exceptions.RequestException as e:
        print(f"Error fetching {link}: {e}")

# Convert data to DataFrame and save to CSV
if data1:
    df1 = pd.DataFrame(data1)
    df1.to_csv("2.csv", index=False)
    

df1

,Product Name,Offer,Product_price,Discount_price,Reviwe,Reting,Delivery
0,2047-WH 2047-WH Working Day and Date Analog Wa...,84% off,"1,599",₹249,(90),4.1,Free delivery
1,141mega 2024-02 Analog Watch - For Men,78% off,998,₹341,(51),3.6,Free delivery
2,Pack of 2 Professional Combo Set Analog Watch ...,92% off,499,₹74,"(12,426)",3.7,Free delivery
3,Stylish Rubber Strap Combo Set Analog Watch -...,40% off,499,₹299,"(2,540)",3.9,Free delivery
4,LED KIDS BLACK WATCH Digital Watch - For Boys...,41% off,599,₹290,"(5,266)",3.5,Free delivery
...,...,...,...,...,...,...,...
647,HM-4192 Day&Date Series Analog Watch - For Men,75% off,999,₹224,(61),3.6,Free delivery
648,D+123 New analog Watches D+123 Analog Watch -...,92% off,599,₹75,"(1,862)",None,Free delivery
649,Analog Watch - For Girls,84% off,999,₹158,(468),None,Free delivery
650,Analog Watch - For Men,85% off,999,₹299,(98),None,Free delivery
651,watches men combo pack 2 Analog Watch - For Men,85% off,899,₹299,"(3,044)",None,Free delivery