In [7]:
import pandas as pd
from tqdm.notebook import tqdm
import requests
from scrapy import Selector

In [8]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
}

In [12]:
url = 'https://en.wikipedia.org/wiki/Talk:African_National_Congress'
response = requests.get(url, headers=headers)
response.status_code

200

In [13]:
sel = Selector(text= response.text)

In [28]:
title = sel.css('span.mw-page-title-main::text').get()

In [29]:
print(title)

African National Congress

In [42]:
content = sel.css('.banner-shell-header b::text').get()

In [43]:
content

'B-class'

In [35]:
cat = sel.css('.wpb-header-combined a::text').getall()

In [36]:
cat

['South Africa',
 'Politics',
 'Africa',
 'Politics',
 'Political parties',
 'Socialism',
 'History']

In [37]:
cat_url = sel.css('.wpb-header-combined a::attr(href)').getall()

In [38]:
cat_url

['/wiki/Wikipedia:WikiProject_South_Africa',
 '/wiki/Wikipedia:WikiProject_South_Africa/Politics_task_force',
 '/wiki/Wikipedia:WikiProject_Africa',
 '/wiki/Wikipedia:WikiProject_Politics',
 '/wiki/Wikipedia:WikiProject_Politics/Political_parties',
 '/wiki/Wikipedia:WikiProject_Socialism',
 '/wiki/Wikipedia:WikiProject_History']

In [46]:
df = pd.DataFrame({'name':title, "url":url, 'content_assessment':content, 'categories':[cat], 'categories_url':[cat_url]})

In [47]:
df

,name,url,content_assessment,categories,categories_url
0,African National Congress,https://en.wikipedia.org/wiki/Talk:African_Nat...,B-class,"[South Africa, Politics, Africa, Politics, Pol...","[/wiki/Wikipedia:WikiProject_South_Africa, /wi..."

In [48]:
cat_dict = {cat[i]: cat_url[i] for i in range(len(cat))}

In [49]:
cat_dict

{'South Africa': '/wiki/Wikipedia:WikiProject_South_Africa',
 'Politics': '/wiki/Wikipedia:WikiProject_Politics',
 'Africa': '/wiki/Wikipedia:WikiProject_Africa',
 'Political parties': '/wiki/Wikipedia:WikiProject_Politics/Political_parties',
 'Socialism': '/wiki/Wikipedia:WikiProject_Socialism',
 'History': '/wiki/Wikipedia:WikiProject_History'}

In [56]:
df = pd.DataFrame({
    'name' : title,
    'url' : url,
    'content_class' : content,
    'categories_and_urls' : [cat_dict]
})

In [57]:
df['categories_and_urls']= df['categories_and_urls'].apply(lambda x: list(x.items()))

In [59]:
df.explode('categories_and_urls')

,name,url,content_class,categories_and_urls
0,African National Congress,https://en.wikipedia.org/wiki/Talk:African_Nat...,B-class,"(South Africa, /wiki/Wikipedia:WikiProject_Sou..."
0,African National Congress,https://en.wikipedia.org/wiki/Talk:African_Nat...,B-class,"(Politics, /wiki/Wikipedia:WikiProject_Politics)"
0,African National Congress,https://en.wikipedia.org/wiki/Talk:African_Nat...,B-class,"(Africa, /wiki/Wikipedia:WikiProject_Africa)"
0,African National Congress,https://en.wikipedia.org/wiki/Talk:African_Nat...,B-class,"(Political parties, /wiki/Wikipedia:WikiProjec..."
0,African National Congress,https://en.wikipedia.org/wiki/Talk:African_Nat...,B-class,"(Socialism, /wiki/Wikipedia:WikiProject_Social..."
0,African National Congress,https://en.wikipedia.org/wiki/Talk:African_Nat...,B-class,"(History, /wiki/Wikipedia:WikiProject_History)"