## Part 1

In [ ]:
import requests                         # for sending HTTP requests

from tqdm.notebook import tqdm, trange  # for progress bars

from scrapy import Selector             # for parsing HTML content

## Part 2

### Step 1
Look Wikipedia Controversial topics page

### Step 2
Extract article links

### Step 3
Visit each article talk page

### Step 4
Locate content assessment box

### Step 5
Extract:
 - article name
 - article url
 - content class
 - categories and url

### Step 6
Store data as dictionary

### Step 7
Convert list of dictionaries into pandas DataFrame

## Part 3

In [14]:
article_url = 'https://en.wikipedia.org/wiki/Meaning_of_life'

In [15]:
headers = {
    'User-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

In [16]:
response = requests.get(article_url, headers=headers)
sel = Selector(text=response.text)

In [17]:
name = sel.css('#firstHeading span::text').get()
print(name)

Meaning of life

In [19]:
talk_url = article_url.replace('/wiki/', '/wiki/Talk:')
response_talk = requests.get(talk_url, headers=headers)
sel_talk = Selector(text=response_talk.text)

In [20]:
texts= sel_talk.css('::text').getall()

content_class = None
for t in texts:
    t = t.strip()
    if "class" in t.lower():
        if "b-class" in t.lower():
            content_class = "B-class"
        elif "c-class" in t.lower():
            content_class = "C-class"
        elif "start-class" in t.lower():
            content_class = "Start-class"
        elif "stub-class" in t.lower():
            content_class = "Stub-class"
print(content_class)

B-class

In [21]:
categories = {}

base_url = 'https://en.wikipedia.org'

for a in sel_talk.css("a"):
    href = a.attrib.get('href', '')
    text = a.css('::text').get()

    if href and "Category:"  in href:
        categories[text] = base_url + href

print(categories)

{'High': 'https://en.wikipedia.org/wiki/Category:High-importance_Religion_articles', 'High-importance': 'https://en.wikipedia.org/wiki/Category:High-importance_Latter_Day_Saint_movement_articles', 'Mid-importance': 'https://en.wikipedia.org/wiki/Category:Mid-importance_Anglicanism_articles', 'Wikipedia controversial topics': 'https://en.wikipedia.org/wiki/Category:Wikipedia_controversial_topics', 'Old requests for peer review': 'https://en.wikipedia.org/wiki/Category:Old_requests_for_peer_review', 'B-Class level-5 vital articles': 'https://en.wikipedia.org/wiki/Category:B-Class_level-5_vital_articles', 'Wikipedia level-5 vital articles in Philosophy and religion': 'https://en.wikipedia.org/wiki/Category:Wikipedia_level-5_vital_articles_in_Philosophy_and_religion', 'B-Class vital articles in Philosophy and religion': 'https://en.wikipedia.org/wiki/Category:B-Class_vital_articles_in_Philosophy_and_religion', 'B-Class Spirituality articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Spirituality_articles', 'High-importance Spirituality articles': 'https://en.wikipedia.org/wiki/Category:High-importance_Spirituality_articles', 'B-Class Philosophy articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Philosophy_articles', 'High-importance Philosophy articles': 'https://en.wikipedia.org/wiki/Category:High-importance_Philosophy_articles', 'B-Class metaphysics articles': 'https://en.wikipedia.org/wiki/Category:B-Class_metaphysics_articles', 'High-importance metaphysics articles': 'https://en.wikipedia.org/wiki/Category:High-importance_metaphysics_articles', 'Metaphysics task force articles': 'https://en.wikipedia.org/wiki/Category:Metaphysics_task_force_articles', 'B-Class ethics articles': 'https://en.wikipedia.org/wiki/Category:B-Class_ethics_articles', 'High-importance ethics articles': 'https://en.wikipedia.org/wiki/Category:High-importance_ethics_articles', 'Ethics task force articles': 'https://en.wikipedia.org/wiki/Category:Ethics_task_force_articles', 'Philosophy articles needing attention': 'https://en.wikipedia.org/wiki/Category:Philosophy_articles_needing_attention', 'B-Class Christianity articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Christianity_articles', 'High-importance Christianity articles': 'https://en.wikipedia.org/wiki/Category:High-importance_Christianity_articles', 'B-Class Catholicism articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Catholicism_articles', 'High-importance Catholicism articles': 'https://en.wikipedia.org/wiki/Category:High-importance_Catholicism_articles', 'WikiProject Catholicism articles': 'https://en.wikipedia.org/wiki/Category:WikiProject_Catholicism_articles', 'B-Class Anglicanism articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Anglicanism_articles', 'Mid-importance Anglicanism articles': 'https://en.wikipedia.org/wiki/Category:Mid-importance_Anglicanism_articles', 'WikiProject Anglicanism articles': 'https://en.wikipedia.org/wiki/Category:WikiProject_Anglicanism_articles', 'B-Class Reformed Christianity articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Reformed_Christianity_articles', 'Unknown-importance Reformed Christianity articles': 'https://en.wikipedia.org/wiki/Category:Unknown-importance_Reformed_Christianity_articles', 'WikiProject Reformed Christianity articles': 'https://en.wikipedia.org/wiki/Category:WikiProject_Reformed_Christianity_articles', 'B-Class Latter Day Saint movement articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Latter_Day_Saint_movement_articles', 'High-importance Latter Day Saint movement articles': 'https://en.wikipedia.org/wiki/Category:High-importance_Latter_Day_Saint_movement_articles', 'WikiProject Latter Day Saint movement articles': 'https://en.wikipedia.org/wiki/Category:WikiProject_Latter_Day_Saint_movement_articles', 'WikiProject Christianity articles': 'https://en.wikipedia.org/wiki/Category:WikiProject_Christianity_articles', 'B-Class Religion articles': 'https://en.wikipedia.org/wiki/Category:B-Class_Religion_articles', 'High-importance Religion articles': 'https://en.wikipedia.org/wiki/Category:High-importance_Religion_articles', 'WikiProject Religion articles': 'https://en.wikipedia.org/wiki/Category:WikiProject_Religion_articles', 'All Wikipedia vital articles': 'https://en.wikipedia.org/wiki/Category:All_Wikipedia_vital_articles'}

In [22]:
import pandas as pd

In [23]:
data = []

In [24]:
data ={
    'name': name,
    'url': article_url,
    'content_assessment_class': content_class,
    'categories ': categories
}

In [25]:
df = pd.DataFrame([data])

In [26]:
df

,name,url,content_assessment_class,categories
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,{'High': 'https://en.wikipedia.org/wiki/Catego...

## Method 1 - json_normalize() (Dictionary to columns)

In [27]:
cat_df = pd.json_normalize(df['categories '])
df_new = pd.concat([df.drop('categories ', axis=1), cat_df], axis=1)    
df_new

,name,url,content_assessment_class,High,High-importance,Mid-importance,Wikipedia controversial topics,Old requests for peer review,B-Class level-5 vital articles,Wikipedia level-5 vital articles in Philosophy and religion,...,Unknown-importance Reformed Christianity articles,WikiProject Reformed Christianity articles,B-Class Latter Day Saint movement articles,High-importance Latter Day Saint movement articles,WikiProject Latter Day Saint movement articles,WikiProject Christianity articles,B-Class Religion articles,High-importance Religion articles,WikiProject Religion articles,All Wikipedia vital articles
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,https://en.wikipedia.org/wiki/Category:High-im...,https://en.wikipedia.org/wiki/Category:High-im...,https://en.wikipedia.org/wiki/Category:Mid-imp...,https://en.wikipedia.org/wiki/Category:Wikiped...,https://en.wikipedia.org/wiki/Category:Old_req...,https://en.wikipedia.org/wiki/Category:B-Class...,https://en.wikipedia.org/wiki/Category:Wikiped...,...,https://en.wikipedia.org/wiki/Category:Unknown...,https://en.wikipedia.org/wiki/Category:WikiPro...,https://en.wikipedia.org/wiki/Category:B-Class...,https://en.wikipedia.org/wiki/Category:High-im...,https://en.wikipedia.org/wiki/Category:WikiPro...,https://en.wikipedia.org/wiki/Category:WikiPro...,https://en.wikipedia.org/wiki/Category:B-Class...,https://en.wikipedia.org/wiki/Category:High-im...,https://en.wikipedia.org/wiki/Category:WikiPro...,https://en.wikipedia.org/wiki/Category:All_Wik...

## Method 2 - explode() (Dictionary to Multiple rows)

In [29]:
df['categories'] = df['categories '].apply(lambda x: list(x.items()))

In [30]:
df_exploded = df.explode('categories')

In [31]:
df_exploded[['category_name', 'category_url']] = pd.DataFrame(df_exploded['categories'].tolist(), index=df_exploded.index)

In [32]:
df_exploded.drop(columns = ['categories '], inplace=True)

In [33]:
df_exploded

,name,url,content_assessment_class,categories,category_name,category_url
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High, https://en.wikipedia.org/wiki/Category:...",High,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance, https://en.wikipedia.org/wik...",High-importance,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(Mid-importance, https://en.wikipedia.org/wiki...",Mid-importance,https://en.wikipedia.org/wiki/Category:Mid-imp...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(Wikipedia controversial topics, https://en.wi...",Wikipedia controversial topics,https://en.wikipedia.org/wiki/Category:Wikiped...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(Old requests for peer review, https://en.wiki...",Old requests for peer review,https://en.wikipedia.org/wiki/Category:Old_req...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class level-5 vital articles, https://en.wi...",B-Class level-5 vital articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,(Wikipedia level-5 vital articles in Philosoph...,Wikipedia level-5 vital articles in Philosophy...,https://en.wikipedia.org/wiki/Category:Wikiped...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,(B-Class vital articles in Philosophy and reli...,B-Class vital articles in Philosophy and religion,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Spirituality articles, https://en.wik...",B-Class Spirituality articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance Spirituality articles, https:...",High-importance Spirituality articles,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Philosophy articles, https://en.wikip...",B-Class Philosophy articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance Philosophy articles, https://...",High-importance Philosophy articles,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class metaphysics articles, https://en.wiki...",B-Class metaphysics articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance metaphysics articles, https:/...",High-importance metaphysics articles,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(Metaphysics task force articles, https://en.w...",Metaphysics task force articles,https://en.wikipedia.org/wiki/Category:Metaphy...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class ethics articles, https://en.wikipedia...",B-Class ethics articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance ethics articles, https://en.w...",High-importance ethics articles,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(Ethics task force articles, https://en.wikipe...",Ethics task force articles,https://en.wikipedia.org/wiki/Category:Ethics_...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(Philosophy articles needing attention, https:...",Philosophy articles needing attention,https://en.wikipedia.org/wiki/Category:Philoso...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Christianity articles, https://en.wik...",B-Class Christianity articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance Christianity articles, https:...",High-importance Christianity articles,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Catholicism articles, https://en.wiki...",B-Class Catholicism articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance Catholicism articles, https:/...",High-importance Catholicism articles,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(WikiProject Catholicism articles, https://en....",WikiProject Catholicism articles,https://en.wikipedia.org/wiki/Category:WikiPro...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Anglicanism articles, https://en.wiki...",B-Class Anglicanism articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(Mid-importance Anglicanism articles, https://...",Mid-importance Anglicanism articles,https://en.wikipedia.org/wiki/Category:Mid-imp...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(WikiProject Anglicanism articles, https://en....",WikiProject Anglicanism articles,https://en.wikipedia.org/wiki/Category:WikiPro...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Reformed Christianity articles, https...",B-Class Reformed Christianity articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,(Unknown-importance Reformed Christianity arti...,Unknown-importance Reformed Christianity articles,https://en.wikipedia.org/wiki/Category:Unknown...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(WikiProject Reformed Christianity articles, h...",WikiProject Reformed Christianity articles,https://en.wikipedia.org/wiki/Category:WikiPro...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Latter Day Saint movement articles, h...",B-Class Latter Day Saint movement articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,(High-importance Latter Day Saint movement art...,High-importance Latter Day Saint movement arti...,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,(WikiProject Latter Day Saint movement article...,WikiProject Latter Day Saint movement articles,https://en.wikipedia.org/wiki/Category:WikiPro...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(WikiProject Christianity articles, https://en...",WikiProject Christianity articles,https://en.wikipedia.org/wiki/Category:WikiPro...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(B-Class Religion articles, https://en.wikiped...",B-Class Religion articles,https://en.wikipedia.org/wiki/Category:B-Class...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(High-importance Religion articles, https://en...",High-importance Religion articles,https://en.wikipedia.org/wiki/Category:High-im...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(WikiProject Religion articles, https://en.wik...",WikiProject Religion articles,https://en.wikipedia.org/wiki/Category:WikiPro...
0,Meaning of life,https://en.wikipedia.org/wiki/Meaning_of_life,B-class,"(All Wikipedia vital articles, https://en.wiki...",All Wikipedia vital articles,https://en.wikipedia.org/wiki/Category:All_Wik...